# Generated by Django 4.2 on 2024-10-27 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Le nom d'utilisateur ne peut contenir que des lettres, des chiffres et les caractères @/./+/-/_", regex='^[\\w.@+-]+$')], verbose_name="Nom d'utilisateur"),
        ),
    ]
