# Generated by Django 4.2 on 2024-10-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
    ]
