# Generated by Django 4.2 on 2024-10-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='rooms/')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('In_progress', 'In_progress')], max_length=20)),
                ('max_participants', models.IntegerField(default=10)),
                ('is_private', models.BooleanField(default=True, verbose_name='Salle Privée')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
